# Generated by Django 5.0.3 on 2024-04-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_category_post',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddConstraint(
            model_name='permission_category_post',
            constraint=models.UniqueConstraint(fields=('post', 'category'), name='unique_post_n_category'),
        ),
    ]
