# Generated by Django 5.0.3 on 2024-04-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='categoryname',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='permission_name',
            new_name='permissionname',
        ),
    ]
