# Generated by Django 5.0.3 on 2024-04-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_rename_category_name_category_categoryname_and_more'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission_Category_Post',
            new_name='PermissionCategoryPost',
        ),
    ]
