# Generated by Django 5.0.3 on 2024-04-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_alter_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permissionname',
            field=models.CharField(blank=True, choices=[('READ_ONLY', 'Read Only'), ('EDIT', 'Read and Edit'), ('NONE', 'None')], null=True, unique=True),
        ),
    ]
