# Generated by Django 5.0.3 on 2024-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_alter_category_categoryname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryname',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('AUTHENTICATED', 'Authenticated'), ('TEAM', 'Team'), ('AUTHOR', 'Author')], default=None),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permissionname',
            field=models.CharField(choices=[('READ_ONLY', 'Read Only'), ('EDIT', 'Read and Edit'), ('NONE', 'None')], default=None),
        ),
    ]
