# Generated by Django 5.0.3 on 2024-04-12 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_alter_category_categoryname_and_more'),
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissioncategorypost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postinverse', to='posts.post'),
        ),
    ]
